title: Digital Barricade Documentation
description: Online management of digital display
theme: just-the-docs

url: https://access.digitalbarricade.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
