title: Digital Barricade
description: Digital Display Online Management System
theme: just-the-docs

url: https://user-manual.digitalbarricade.com

aux_links:
  Go to Site: https://access.digitalbarricade.com
