title: Digital Barricade Documentation
description: Digital Display Online Management System
theme: just-the-docs

url: https://user-manual.digitalbarricade.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
