title: Digital Barricade Documentation
description: Digital Display Online Management System
theme: just-the-docs

url: https://user-manual.digitalbarricade.com

aux_links:
  Let's Start: https://access.digitalbarricade.com
